apiVersion: apps/v1
kind: Deployment
metadata:
  name:  redis-leader
  labels:
    app:  redis
    role: leader
    tier: backend
spec:
  selector:
    matchLabels:
      app: redis
  replicas: 1
  template:
    metadata:
      labels:
        app:  redis
        role: leader
        tier: backend
    spec:
      containers:
      - name:  leader
        image: "docker.io/redis:6.0.5"
        ports:
        - containerPort:  6379