apiVersion: v1
kind: Service
metadata:
  name: redis-leader
  namespace: default
  labels:
    app: redis
    role: leader
spec:
  selector:
    app: redis
    role: leader
  ports:
  - port: 6379
    targetPort: 6379