apiVersion: apps.danielhu.cn/v1
kind: Application
metadata:
  labels:
    app: nginx
  name: application-sample
spec:
  # TODO(user): Add fields here
  replicas: 3
  template:
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.2
          ports:
            - containerPort: 80
