configMapGenerator:
- name: app-config
  files:
  - config.txt
secretGenerator:
- name: app-secret
  files:
  - password.txt
resources:
  - nginx-deployment.yaml
  - nginx-service.yaml
patchesStrategicMerge:
  - nginx-memory.yaml
patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: nginx
    path: patch.yaml

generatorOptions:
  disableNameSuffixHash: true
namespace: default
namePrefix: app-
nameSuffix: -v1
commonLabels:
  version: v1
commonAnnotations:
  owner: anoyer
